name: hadsp_env
channels:
  - pytorch
  - conda-forge
dependencies:
  - python>=3.11
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - pandas
  - scikit-learn
  - librosa
  - pytorch  # 'torch' is named 'pytorch' in conda
  - torchaudio
  - aeon>=0.10
  - ffmpeg
  - tensorflow
  - optuna
  - jupyterlab
  - tqdm
  - pip
  - pip:
    - reservoirpy
    - jupyterlab-execute-time
    - jupyterlab-optuna